apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: php-test
  name: php-test
  namespace: pipeline-0
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: php-test
    deploymentconfig: php-test
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: php-test
        deploymentconfig: php-test
    spec:
      containers:
        - env:
            - name: VAR_EXAMPLE
              value: anywhere
          image: >-
            gdocker.io/gloriapg/php:latest
          imagePullPolicy: IfNotPresent
          name: php-test
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
